modified-repo:
- '*'

modified-client:
- src/client/**/*

modified-server:
- src/server/**/*

modified-api:
- src/shared/Modules/**/*
- src/shared/Classes/**/*

modified-util:
- src/first/**/*
- src/utility/**/*
