# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.2.1"
wally = "UpliftGames/wally@0.3.1"
selene = "Kampfkarren/selene@0.24.0"
run-in-roblox = "reimakesgames/run-in-roblox@0.3.3"
luau-lsp = "JohnnyMorganz/luau-lsp@1.14.3"
lune = "filiptibell/lune@0.6.5"
moonwave-extractor = "evaera/moonwave@1.0.1"
# rojo = "rojo-rbx/rojo@6.2.0"
