site_name: Documentation and Contribution Guide
site_url: https://hybrid-conflict.vercel.app/
site_description: Documentation and Contribution Guide for Hybrid Conflict
site_author: reimakesgames

copyright: © 2022-2023 reimakesgames. All rights reserved.

repo_url: https://github.com/reimakesgames/hybrid-conflict
repo_name: GitHub

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - markdown_include.include:
      base_path: docs

nav:
  - index.md
  - Contribution:
    - contribution/installation.md
    - contribution/branches.md
    - contribution/pull_requests.md
    - contribution/unit_tests.md
  - Documentation:
    - Classes:
      - documentation/classes/Animator.md

theme:
  name: material
  font:
    text: Poppins
    code: Ubuntu Mono
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reimakesgames/hybrid-conflict
      name: Game Repository
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Shiroi7264
      name: reimakesgames' Twitter Page
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CjUWSVKhP3
      name: reimakesgames Community Server
