[package]
name = "reimakesgames/hybrid-conflict"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
testez = "roblox/testez@0.4.1"
fastsignal = "lucasmzreal/fastsignal@10.2.1"
janitor = "howmanysmall/janitor@1.14.1"
fastcastredux = "encodedvenom/fastcastredux@0.1.3"
promise = "evaera/promise@4.0.0"
prisma = "reimakesgames/prisma@0.2.1"
link = "reimakesgames/link@0.2.4"
