[package]
name = "reimakesgames/hybrid-conflict"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
FastSignal = "lucasmzreal/fastsignal@10.2.1"
BridgeNet2 = "ffrostflame/bridgenet2@0.1.0"
Janitor = "howmanysmall/janitor@1.15.1"
Promise = "evaera/promise@4.0.0"
FastCastRedux = "encodedvenom/fastcastredux@0.1.3"
TestEZ = "roblox/testez@0.4.1"
